name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+rc[0-9]+'

jobs:
  deploy:    
    runs-on: ubuntu-latest
    steps:
      - name: Check out tag
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build artifacts
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Generate release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/libs/amcdb-${{ github.ref_name }}+1.[0-9][0-9].[0-9].jar
          fail_on_unmatched_files: true
          generate_release_notes: true
